spring.profiles.include=local

server.port=${SERVER_PORT:7893}

spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/car_agents?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root}

spring.data.redis.host=${REDIS_HOST:127.0.0.1}
spring.data.redis.password=${REDIS_PASSWORD:123456}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.database=${REDIS_DATABASE:2}
